### ISSUE TITLE
Integration doesn't work after update to v1.2.9

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#19]
The integration is not working at all after the latest update.
I get the following entry in my log:

```
Logger: audiconnectpy.models
Source: custom_components/audiconnect/coordinator.py:47
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 13:10:21 (12 occurrences)
Last logged: 13:15:35
 
Unable to update vehicle data cyclic of XXXXXXXXXXXXXX: 'NoneType' object is not iterable
```

It might have something to do that the new configuration flow is not working:

```
Logger: custom_components.audiconnect.config_flow
Source: config_entries.py:1475
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 13:11:49 (5 occurrences)
Last logged: 13:15:49

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/config_flow.py", line 41, in async_step_user
    self._async_abort_entries_match(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1515, in _async_abort_entries_match
    _async_abort_entries_match(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1475, in _async_abort_entries_match
    raise data_entry_flow.AbortFlow("already_configured")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured
```

<img width="332" alt="image" src="https://github.com/cyr-ius/hass-audiconnect/assets/115901851/eca25ff1-0d1a-4176-a648-7acc9f88fdbd">

Can you provide any help?

**Comment by simonepittis** [comment]
+1 same problem, rollback to v 1.0.7

**Comment by simonepittis** [comment]
2023-06-12 10:42:28.325 DEBUG (MainThread) [audiconnectpy.auth] REQUEST: https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/tripstatistics/v1/Audi/NO/vehicles/WAUZZZGE8MB002220/tripdata/cyclic
2023-06-12 10:42:28.491 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE HEADERS: <CIMultiDictProxy('X-FS-Tracking-ID': '19841f62-688c-4e2f-a7bf-4b3d6b46333f', 'Content-Encoding': 'gzip', 'Content-Type': 'application/vnd.vwg.mbb.TripDataList_v1_0_0+xml;charset=utf-8', 'Date': 'Mon, 12 Jun 2023 08:42:28 GMT', 'Server': 'www')>
2023-06-12 10:42:28.491 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE:  ,return_code '204'
2023-06-12 10:42:28.491 DEBUG (MainThread) [audiconnectpy.auth] JSON FIX: Accept is JSON but Response is None
2023-06-12 10:42:28.492 ERROR (MainThread) [audiconnectpy.models] Unable to update vehicle data cyclic of WAUZZZGE8MB002220: 'NoneType' object is not iterable
2023-06-12 10:42:28.494 DEBUG (MainThread) [custom_components.audiconnect.coordinator] Finished fetching audiconnect data in 10.537 seconds (success: False)

**Comment by simonepittis** [comment]
2023-06-12 10:42:28.325 DEBUG (MainThread) [audiconnectpy.auth] REQUEST: https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/tripstatistics/v1/Audi/NO/vehicles/WAUXXXXXXXXXXXX2220/tripdata/cyclic
2023-06-12 10:42:28.491 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE HEADERS: <CIMultiDictProxy('X-FS-Tracking-ID': '19841f62-688c-4e2f-a7bf-4b3d6b46333f', 'Content-Encoding': 'gzip', 'Content-Type': 'application/vnd.vwg.mbb.TripDataList_v1_0_0+xml;charset=utf-8', 'Date': 'Mon, 12 Jun 2023 08:42:28 GMT', 'Server': 'www')>
2023-06-12 10:42:28.491 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE: ,return_code '204'
2023-06-12 10:42:28.491 DEBUG (MainThread) [audiconnectpy.auth] JSON FIX: Accept is JSON but Response is None
2023-06-12 10:42:28.492 ERROR (MainThread) [audiconnectpy.models] Unable to update vehicle data cyclic of WAUXXXXXXXXXXXX2220: 'NoneType' object is not iterable
2023-06-12 10:42:28.494 DEBUG (MainThread) [custom_components.audiconnect.coordinator] Finished fetching audiconnect data in 10.537 seconds (success: False)

not fixed

**Comment by simonepittis** [comment]
> > +1 same problem, rollback to v 1.0.7
> 
> Fix in 1.3.0 , please try again

looks better.... but we miss a lot of sensors

![image](https://github.com/cyr-ius/hass-audiconnect/assets/92569194/3cf2c935-47fb-40d4-a4d4-ae638f9f0ac9)


![image](https://github.com/cyr-ius/hass-audiconnect/assets/92569194/7ef7cf41-0752-4f39-ad87-36dca6c5fb25)

**Comment by Kolbi** [comment]
The sensors are renamed. The example from the readme has to be adapted.

**Comment by Kolbi** [comment]
1.3.0 is working for me.

**Comment by simonepittis** [comment]
ok... updated all automations and cards with the new names..... and works

**Comment by Kolbi** [comment]
My example for hybrid:
`type: picture-elements
image: /local/audi.png
elements:
  - type: state-icon
    icon: mdi:car-door
    entity: lock.audi_a6_avant_tfsi_e_any_door_unlocked
    tap_action:
      action: toggle
    style:
      left: 12%
      top: 86%
      '--paper-item-icon-color': black
      '--paper-item-icon-active-color': red
  - type: state-label
    entity: lock.audi_a6_avant_tfsi_e_any_door_unlocked
    style:
      color: black
      left: 12%
      top: 95%
  - type: icon
    entity: sensor.audi_a6_avant_tfsi_e_utc_time_and_kilometer_status
    icon: mdi:speedometer
    style:
      color: black
      left: 32%
      top: 86%
  - type: state-label
    entity: sensor.audi_a6_avant_tfsi_e_utc_time_and_kilometer_status
    style:
      color: black
      left: 32%
      top: 95%
  - type: icon
    icon: mdi:window-open
    entity: binary_sensor.audi_a6_avant_tfsi_e_any_window_open
    style:
      color: black
      left: 52%
      top: 86%
  - type: state-label
    entity: binary_sensor.audi_a6_avant_tfsi_e_any_window_open
    style:
      color: black
      left: 52%
      top: 95%
  - type: icon
    icon: mdi:room-service-outline
    entity: sensor.audi_a6_avant_tfsi_e_maintenance_interval_distance_to_inspection
    style:
      color: black
      left: 72%
      top: 86%
  - type: state-label
    entity: sensor.audi_a6_avant_tfsi_e_maintenance_interval_distance_to_inspection
    style:
      color: black
      left: 72%
      top: 95%
  - type: state-icon
    icon: mdi:tire
    entity: binary_sensor.audi_a6_avant_tfsi_e_any_tyre_problem
    style:
      color: black
      left: 90%
      top: 86%
      '--paper-item-icon-color': black
      '--paper-item-icon-active-color': red
  - type: state-label
    entity: binary_sensor.audi_a6_avant_tfsi_e_any_tyre_problem
    style:
      color: black
      left: 90%
      top: 95%
#  - type: state-badge
#    entity: sensor.audi_a6_avant_tfsi_e_charging_state
#    style:
#      color: transparent
#      left: 1%
#      top: 1%
#      transform: scale(0.7,0.7)
#      '--label-badge-red': green
#      '--label-badge-background-color': transparent
#      '--ha-label-badge-label-color': black
#      '--label-badge-text-color': green
  - type: state-badge
    entity: sensor.audi_a6_avant_tfsi_e_tank_level_in_percentage
    style:
      color: transparent
      left: 1%
      top: 25%
      transform: scale(0.7,0.7)
      '--label-badge-red': gray
      '--label-badge-background-color': transparent
      '--ha-label-badge-label-color': black
      '--label-badge-text-color': black
  - type: state-badge
    entity: sensor.audi_a6_avant_tfsi_e_state_of_charge
    style:
      color: transparent
      left: 1%
      top: 50%
      transform: scale(0.7,0.7)
      '--label-badge-red': green
      '--label-badge-background-color': transparent
      '--ha-label-badge-label-color': black
      '--label-badge-text-color': green
  - type: state-badge
    entity: sensor.audi_a6_avant_tfsi_e_total_range
    style:
      color: transparent
      right: 1%
      top: 1%
      transform: scale(0.7,0.7)
      '--label-badge-red': grey
      '--label-badge-background-color': transparent
      '--ha-label-badge-label-color': black
      '--label-badge-text-color': black
  - type: state-badge
    entity: sensor.audi_a6_avant_tfsi_e_primary_engine_range
    style:
      color: transparent
      right: 1%
      top: 25%
      transform: scale(0.7,0.7)
      '--label-badge-red': gray
      '--label-badge-background-color': transparent
      '--ha-label-badge-label-color': black
      '--label-badge-text-color': black
  - type: state-badge
    entity: sensor.audi_a6_avant_tfsi_e_secondary_engine_range
    style:
      color: transparent
      right: 1%
      top: 50%
      transform: scale(0.7,0.7)
      '--label-badge-red': green
      '--label-badge-background-color': transparent
      '--ha-label-badge-label-color': black
      '--label-badge-text-color': green
`
