### ISSUE TITLE
Is the API broken again? Have tried removing and reading but it’s failing. 

### ISSUE THREAD

**Issue by agentadam-code** [cyr-ius/hass-audiconnect#21]
Error

Logger: custom_components.audiconnect.coordinator
Source: custom_components/audiconnect/coordinator.py:47 
Integration: Audi Connect 
First occurred: 05:50:39 (306 occurrences) 
Last logged: 13:22:58

Unexpected error fetching audiconnect data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 47, in _async_update_data
    await self.api.async_update()
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/api.py", line 58, in async_update
    for response in vehicles_response.getr("data.userVehicles", []):
TypeError: 'NoneType' object is not iterable

**Comment by jjslegacy** [comment]
I am seeing the same issue.  Had the older version of this integration.  removed all and switched to this fork but when I try to add the integration I see:

2023-08-15 12:53:43.501 ERROR (MainThread) [custom_components.audiconnect.coordinator] Unexpected error fetching audiconnect data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 47, in _async_update_data
    await self.api.async_update()
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/api.py", line 58, in async_update
    for response in vehicles_response.getr("data.userVehicles", []):
TypeError: 'NoneType' object is not iterable

**Comment by jjslegacy** [comment]
more debugging info:
, 'Content-Type': 'application/json', 'X-User-Country': 'US'}
2023-08-15 13:24:31.490 DEBUG (MainThread) [audiconnectpy.auth] REQUEST: https://app-api.live-my.audi.com/vgql/v1/graphql
2023-08-15 13:24:31.642 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE HEADERS: <CIMultiDictProxy('x-powered-by': 'Express', 'Vary': 'Origin', 'Access-Control-Allow-Credentials': 'true', 'Etag': 'W/"135-E18pyVaMzsRNNDARHkMG73w86FI"', 'x-envoy-upstream-service-time': '29', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'x-request-id': '935a9154-b360-4a39-9299-4b42269708d2', 'Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '223', 'Server': 'istio-envoy', 'Date': 'Tue, 15 Aug 2023 17:24:31 GMT', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-myaudi': 'm1')>
2023-08-15 13:24:31.643 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE: {"errors":[{"message":" Unauthorized","locations":[{"line":2,"column":2}],"path":["userVehicles"],"extensions":{"code":"UNAUTHENTICATED","response":{"status":401,"statusText":"Unauthorized","body":{"errorMessage":"Error in downstream service","vudsErrorCode":"UNAUTHORIZED"}}}}],"data":{"userVehicles":null}}
 ,return_code '200'

**Comment by rebel7580** [comment]
After removing the old arjenvrh version and copying this one to audiconnect folder, I get the same error:

```
Source: custom_components/audiconnect/coordinator.py:47
Integration: Audi Connect (documentation, issues)
First occurred: 4:45:02 PM (20 occurrences)
Last logged: 4:59:16 PM

Unexpected error fetching audiconnect data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/audiconnect/coordinator.py", line 47, in _async_update_data
    await self.api.async_update()
  File "/usr/local/lib/python3.10/site-packages/audiconnectpy/api.py", line 58, in async_update
    for response in vehicles_response.getr("data.userVehicles", []):
TypeError: 'NoneType' object is not iterable
```
