### ISSUE TITLE
Unable to switch on climatisation

### ISSUE THREAD

**Issue by oleg-d** [cyr-ius/hass-audiconnect#32]
I am having trouble switching on my climatisation from HA with this integration. Otherwise it's working great pulling the data.

At first I had some PIN issues but figured it out and now locking the doors work, but pre-heating cannot be enabled.

Any suggestions on what to try. Here's the log of trying to toggle the climatisation off in HA.

```
2023-11-12 09:58:43.493 DEBUG (MainThread) [audiconnectpy.auth] REQUEST HEADERS: {'Accept': 'application/json', 'Accept-Charset': 'utf-8', 'User-Agent': 'okhttp/3.11.0', 'X-App-Name': 'myAudi', 'X-App-Version': '4.13.0', 'Authorization': 'Bearer <REDACTED>', 'X-Client-ID': '9bd08a9f-3589-4c93-9b76-ca1ab64ebc5e'}
2023-11-12 09:58:43.493 DEBUG (MainThread) [audiconnectpy.auth] REQUEST: https://mal-1a.prd.ece.vwg-connect.com/api/rolesrights/authorization/v2/vehicles/WAUZZZGE5LB011052/services/rclima_v1/operations/P_QSTOPACT/security-pin-auth-requested
2023-11-12 09:58:43.821 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE HEADERS: <CIMultiDictProxy('X-FS-Tracking-ID': '7c634fa8-c42c-47df-81db-921cffd023f3', 'Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '650', 'Date': 'Sun, 12 Nov 2023 07:58:43 GMT', 'Server': 'www')>
2023-11-12 09:58:43.821 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE: {"securityPinAuthInfo":{"securityToken":"<REDACTED>","securityPinTransmission":{"hashProcedureVersion":2,"challenge":"34E39F137FE281B29B45510E470DAAF198945FE5D85C38317336D15093CD42FD"},"remainingTries":3}} ,return_code '200'
2023-11-12 09:58:43.822 DEBUG (MainThread) [audiconnectpy.auth] REQUEST HEADERS: {'Accept': 'application/json', 'Accept-Charset': 'utf-8', 'User-Agent': 'okhttp/3.11.0', 'X-App-Name': 'myAudi', 'X-App-Version': '4.13.0', 'Authorization': 'Bearer <REDACTED>', 'X-Client-ID': '9bd08a9f-3589-4c93-9b76-ca1ab64ebc5e', 'Content-Type': 'application/json'}
2023-11-12 09:58:43.822 DEBUG (MainThread) [audiconnectpy.auth] REQUEST: https://mal-1a.prd.ece.vwg-connect.com/api/rolesrights/authorization/v2/security-pin-auth-completed
2023-11-12 09:58:44.003 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE HEADERS: <CIMultiDictProxy('X-FS-Tracking-ID': 'fdbb2c94-8a5b-4901-9252-f8b0d1f233c6', 'Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '534', 'Date': 'Sun, 12 Nov 2023 07:58:43 GMT', 'Server': 'www')>
2023-11-12 09:58:44.003 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE: {"securityToken":"<REDACTED>"} ,return_code '200'
2023-11-12 09:58:44.003 DEBUG (MainThread) [audiconnectpy.auth] REQUEST HEADERS: {'Accept': 'application/json', 'Accept-Charset': 'utf-8', 'User-Agent': 'okhttp/3.11.0', 'X-App-Name': 'myAudi', 'X-App-Version': '4.13.0', 'Authorization': 'Bearer <REDACTED>', 'X-Client-ID': '9bd08a9f-3589-4c93-9b76-ca1ab64ebc5e', 'Content-Type': 'application/vnd.vwg.mbb.ClimaterAction_v1_0_0+xml', 'x-mbbSecToken': '<REDACTED>'}
2023-11-12 09:58:44.003 DEBUG (MainThread) [audiconnectpy.auth] REQUEST: https://msg.volkswagen.de/fs-car/bs/climatisation/v1/Audi/FI/vehicles/WAUZZZGE5LB011052/climater/actions
2023-11-12 09:58:44.345 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE HEADERS: <CIMultiDictProxy('x-fault-id': '7400ab99-ea77-4e42-a927-ed92623ffecd', 'X-FS-Tracking-ID': '05d66d5c-f1b2-401f-bedf-a374b0ce61fd', 'X-FS-Error-Code': 'GW406', 'Content-Type': 'application/json', 'Content-Length': '87', 'Date': 'Sun, 12 Nov 2023 07:58:44 GMT', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff')>
2023-11-12 09:58:44.345 DEBUG (MainThread) [audiconnectpy.auth] RESPONSE: {"error":{"errorCode":"climatisation.bs.notacceptable","description":"Not Acceptable"}} ,return_code '406'
2023-11-12 09:58:44.346 ERROR (MainThread) [custom_components.audiconnect.switch] Error to turn off : (406, {'error': {'errorCode': 'climatisation.bs.notacceptable', 'description': 'Not Acceptable'}})

```

**Comment by Heelderpeel** [comment]
same problem for me.

(403, {'error': {'errorCode': 'mbbc.rolesandrights.securityPinLocked', 'description': 'The Security PIN is currently locked.', 'details': {'challenge': '', 'user': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'reason': 'SECURITY_PIN_LOCKED', 'delay': '86220', 'remainingTries': '0'}}})

**Comment by oleg-d** [comment]
> same problem for me.
> 
> (403, {'error': {'errorCode': 'mbbc.rolesandrights.securityPinLocked', 'description': 'The Security PIN is currently locked.', 'details': {'challenge': '', 'user': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'reason': 'SECURITY_PIN_LOCKED', 'delay': '86220', 'remainingTries': '0'}}})

@Heelderpeel security pin errors are not related to the integration, they are real errors returned by the audi api.
i had "pin locked" and that went away after i waited more than 24 hrs and re-added the integration with my correct pin. which was the 4-digit one i set up in the myaudi phone app.

**Comment by hjaltij** [comment]
I'm having the same issue.

**Comment by cyr-ius** [comment]
Please test 1.3.2

**Comment by coreywillwhat** [comment]
@cyr-ius I tried 1.3.2 with audiconnectpy 1.4.5 and the only service i could get to work was the refresh and turn on|off "lock".
It seems from the logs, some of the services aren't available for my vehicle type. 2021 Audi Q5 PHEV. For clarity, the climater works for my vehicle on the arjenvrh branch. VIN removed from logs.

**climate**: `2023-12-28 07:49:19.340 ERROR (MainThread) [custom_components.audiconnect.services] (406, {'error': {'errorCode': 'climatisation.bs.notacceptable', 'description': 'HTTP 406 Not Acceptable'}})`

**charger**: `2023-12-28 07:49:56.396 ERROR (MainThread) [custom_components.audiconnect.services] (400, {'error': {'errorCode': 'gw.error.validation', 'description': 'Invalid Request'}})`

**preheater**: `2023-12-28 07:50:43.735 ERROR (MainThread) [custom_components.audiconnect.services] (502, {'error': {'errorCode': 'RS.security.9007', 'description': 'The service: rheating_v1 for VIN: XXXXXXXXXXXXX could not be found.'}})`

**window heating**: `2023-12-28 07:51:29.940 ERROR (MainThread) [custom_components.audiconnect.services] (403, {'error': {'errorCode': 'climatisation.auth.forbidden', 'description': 'The context was invalid, deduced from the fact that there are no security requirements for the combination of service, operation and channel stored in MBB R&R.'}})`

**ventilation**: `2023-12-28 07:52:09.896 ERROR (MainThread) [custom_components.audiconnect.services] (502, {'error': {'errorCode': 'RS.security.9007', 'description': 'The service: rheating_v1 for VIN: XXXXXXXXXXXXX could not be found.'}})`

FWIW: I also tried audiconnectpy 1.4.6 and got an immediate error with 3 different attempts, 1 of which was updating the climater temp:
```
2023-12-28 07:01:28.004 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140546398815680] 'method' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/audiconnect/switch.py", line 73, in async_turn_on
    await getattr(
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/services.py", line 382, in async_climater
    "heaterSource": self.set_heater_source[vin],
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
2023-12-28 07:02:06.909 ERROR (MainThread) [custom_components.audiconnect.switch] Error to turn off : (400, {'error': {'errorCode': 'gw.error.validation', 'description': 'Invalid payload'}})
2023-12-28 07:02:12.998 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140546398815680] 'method' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/audiconnect/switch.py", line 73, in async_turn_on
    await getattr(
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/services.py", line 382, in async_climater
    "heaterSource": self.set_heater_source[vin],
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 106, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/audiconnect/number.py", line 80, in async_set_native_value
    await getattr(
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/services.py", line 421, in async_climater_temp
    "heaterSource": self.set_heater_source[vin],
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
```

**Comment by coreywillwhat** [comment]
Considering a new release wasn't posted i wasn't expecting it to work, but gave the latest unreleased code a try which points to audiconnectpy 1.4.7.

**climater**: `2023-12-29 07:32:12.075 ERROR (MainThread) [custom_components.cyrius-audiconnect.services] (400, {'error': {'errorCode': 'gw.error.validation', 'description': 'Invalid payload'}})`

**window heating**: `2023-12-29 07:33:42.731 ERROR (MainThread) [custom_components.cyrius-audiconnect.services] (403, {'error': {'errorCode': 'climatisation.auth.forbidden', 'description': 'The context was invalid, deduced from the fact that there are no security requirements for the combination of service, operation and channel stored in MBB R&R.'}})`

**charger**: `2023-12-29 07:39:01.575 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'Vehicle' object has no attribute 'async_set_charger'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cyrius-audiconnect/services.py", line 58, in async_turn_on_action
    await async_actions(vin, action, True)
  File "/config/custom_components/cyrius-audiconnect/services.py", line 70, in async_actions
    await vehicle.async_set_charger(mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Vehicle' object has no attribute 'async_set_charger'`

**ventilation**: `2023-12-29 07:41:57.053 ERROR (MainThread) [custom_components.cyrius-audiconnect.services] (502, {'error': {'errorCode': 'RS.security.9007', 'description': 'The service: rheating_v1 for VIN: XXXXXXXXXXXX could not be found.'}})`

**pre-heating**: `2023-12-29 07:42:30.644 ERROR (MainThread) [custom_components.cyrius-audiconnect.services] (400, {'error': {'errorCode': 'gw.error.validation', 'description': 'Invalid Request'}})`

**Comment by cyr-ius** [comment]
Please try 1.4.1

**Comment by coreywillwhat** [comment]
Turn on: Climater
**API Level 2**
```
2023-12-29 12:01:23.285 ERROR (MainThread) [custom_components.audiconnect.services] (400, {'error': {'errorCode': 'gw.error.validation', 'description': 'Invalid payload'}})
```
**API Level 3:**
```
2023-12-29 12:01:53.007 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Session is closed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/services.py", line 58, in async_turn_on_action
    await async_actions(vin, action, True)
  File "/config/custom_components/audiconnect/services.py", line 68, in async_actions
    await vehicle.async_set_climater(mode)
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/actions.py", line 59, in async_set_climater
    security_token = await self._async_get_security_token(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/actions.py", line 425, in _async_get_security_token
    rsp = await self.auth.get(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/auth.py", line 138, in get
    response = await self.request(METH_GET, url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/auth.py", line 91, in request
    response = await self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 421, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
2023-12-29 12:01:53.017 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140540154692672] Error handling message: Unknown error (unknown_error) **REDACTED FIRST NAME LAST NAME** from **REDACTED LOCAL IP** (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 782, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/services.py", line 58, in async_turn_on_action
    await async_actions(vin, action, True)
  File "/config/custom_components/audiconnect/services.py", line 68, in async_actions
    await vehicle.async_set_climater(mode)
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/actions.py", line 59, in async_set_climater
    security_token = await self._async_get_security_token(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/actions.py", line 425, in _async_get_security_token
    rsp = await self.auth.get(
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/auth.py", line 138, in get
    response = await self.request(METH_GET, url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/auth.py", line 91, in request
    response = await self._session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 421, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

**Comment by cyr-ius** [comment]
OK, I finally found the bug for calls. Please try version 1.5.0

**Comment by coreywillwhat** [comment]
I had a strange error "can't connect to API" during integration install, when trying to submit my credentials/region/pin. Haven't seen that before. 3rd time hitting 'submit' worked, so maybe just a local issue.

After setup, **I was able to turn on and off the Climater**! This was on the default API Level 2. I think this would resolve this specific issue.

That said, trying some of the other commands:
**Lock/Unlock** still works.

**Windows Heating** - I have "Glass Surface Heating" in the Audi App controls:
2023-12-30 07:19:25.989 ERROR (MainThread) [custom_components.audiconnect.services] (403, {'error': {'errorCode': 'climatisation.auth.forbidden', 'description': 'The context was invalid, deduced from the fact that there are no security requirements for the combination of service, operation and channel stored in MBB R&R.'}})

**Charger** - I have "Charging" in the Audi App controls:
2023-12-30 07:23:13.594 ERROR (MainThread) [custom_components.audiconnect.services] (406, {'error': {'errorCode': 'batterycharge.bs.notacceptable', 'description': 'HTTP 406 Not Acceptable'}})

**Ventilation** - I have "Auto Seat Comfort" in the Audi App Controls:
2023-12-30 07:26:19.843 ERROR (MainThread) [custom_components.audiconnect.services] (400, {'error': {'errorCode': 'gw.error.validation', 'description': 'Invalid Request'}})

**Pre-Heating** I don't think this is available for my car:
2023-12-30 07:27:11.557 ERROR (MainThread) [custom_components.audiconnect.services] (502, {'error': {'errorCode': 'RS.security.9007', 'description': 'The service: rheating_v1 for VIN: XXXXXXXXXXXXX could not be found.'}})

I'd love to be able to turn the seat heater and glass surface heating on, as I live in a very cold environment most of the year, but the climater is a big win! Let me know how I can buy you a coffee.

Here is my diagnostic file and some quick screenshots to show the options available for my car to be sure we're not chasing something I don't have available.

[config_entry-audiconnect-5091b6d733558fcc1c6f915f4efc7bdd.json.txt](https://github.com/cyr-ius/hass-audiconnect/files/13798321/config_entry-audiconnect-5091b6d733558fcc1c6f915f4efc7bdd.json.txt)
![signal-2023-12-30-073400_002](https://github.com/cyr-ius/hass-audiconnect/assets/104224685/58c7bcc4-bdec-4988-a204-cd1cdfa8e2e3)
![signal-2023-12-30-073425_002](https://github.com/cyr-ius/hass-audiconnect/assets/104224685/0756100c-44f5-48aa-a663-bae277a68b29)
![signal-2023-12-30-073510_002](https://github.com/cyr-ius/hass-audiconnect/assets/104224685/d5157110-4ebd-4eaa-9988-3d3dcd24fc12)

**Comment by hjaltij** [comment]
@coreywillwhat Are you testing the audiconnect module/package directly or using this via HA? I’d like to give this new version a spin but it’s not showing up for me as an update.

I could slso help making patches if I got the right env setup.

@cyr-ius Are you using the Android app for reverse engineering the API? I tried mitm on the iOS app but it’s using cert pinning so it’s a bit more tricky to reverse engineer.

**Comment by oleg-d** [comment]
Just tried out v1.4.5 on HA and my climater can now be turned on e-tron! Yay!! Absolute legend cyr-ius.

I too have those window heating and seat heating options but haven't checked what the situation is there if they're on or not. Literally just happy enough that the climater can be turned on.

**Comment by coreywillwhat** [comment]
> @coreywillwhat Are you testing the audiconnect module/package directly or using this via HA? I’d like to give this new version a spin but it’s not showing up for me as an update.
> 
> I could slso help making patches if I got the right env setup.
> 
> @cyr-ius Are you using the Android app for reverse engineering the API? I tried mitm on the iOS app but it’s using cert pinning so it’s a bit more tricky to reverse engineer.

I'm testing in HA. You can always download the zipped code from here, unzip, and copy/overwrite the audiconnect folder in your custom_components folder if you need to. That said, I see the update in HACS. Strange you aren't seeing it.

**Comment by hjaltij** [comment]
Got it. Thanks!!

**Comment by cyr-ius** [comment]
I just added two APIs for preheats and load

@oleg-d : Try with API level 2 to see if the window preheating works

**Comment by hjaltij** [comment]
Sorry, but what is API level 2?

**Comment by coreywillwhat** [comment]
> Sorry, but what is API level 2?

My understanding is different vehicles have different APIs, so @cyr-ius is creating a way to try different APIs for your vehicles features to fine tune it to work.

Go to Settings > Integrations > Audi Connect > Configure > Select your vehicle in drop down > Submit > change API Levels for different features to test which works for yours > submit > Save & Exit > Submit.

**Comment by hjaltij** [comment]
@coreywillwhat Thank you!

**Comment by coreywillwhat** [comment]
Error Trying to Adjust Climatisation Target Temp:
```
2024-01-04 16:30:33.279 ERROR (MainThread) [custom_components.audiconnect.number] Error to set value: (403, {'error': {'errorCode': 'climatisation.auth.forbidden', 'description': 'The context was invalid, deduced from the fact that there are no security requirements for the combination of service, operation and channel stored in MBB R&R.'}})
```
