### ISSUE TITLE
Unexpected error fetching audiconnect data: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ecodweeb** [cyr-ius/hass-audiconnect#33]
Hello,

I am getting the following error when I attempt to add my account into the integration. 

```
Logger: custom_components.audiconnect.coordinator
Source: helpers/update_coordinator.py:290
Integration: Audi Connect ([documentation](https://github.com/cyr-ius/hass-audiconnect), [issues](https://github.com/cyr-ius/hass-audiconnect/issues))
First occurred: 2:03:30 PM (5 occurrences)
Last logged: 2:07:29 PM

Unexpected error fetching audiconnect data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 47, in _async_update_data
    await self.api.async_update()
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/api.py", line 58, in async_update
    for response in vehicles_response.getr("data.userVehicles", []):
TypeError: 'NoneType' object is not iterable
```

**Comment by mesa72** [comment]
I am experiencing this issue as well. When testing audiconnectpy I received the following in the logs. I am in US region if that helps. Please let me know if I can provide any additional debugging help.

Thanks!

`2023-11-14 12:29:40,828 - audiconnectpy.auth - DEBUG - REQUEST: https://app-api.live-my.audi.com/vgql/v1/graphql
2023-11-14 12:29:41,478 - audiconnectpy.auth - DEBUG - RESPONSE: {"errors":[{"message":" Unauthorized","locations":[{"line":2,"column":2}],"path":["userVehicles"],"extensions":{"code":"UNAUTHENTICATED","response":{"status":401,"statusText":"Unauthorized","body":{"errorMessage":"Error in downstream service","vudsErrorCode":"VUDS_401_INCORRECT_REGION_ERROR"}}}}],"data":{"userVehicles":null}}`

**Comment by tamahome23** [comment]
Exact same issue for me that [ecodweeb] shared.  Logs are line for line same report.  Have the most recent update from here that says it addresses it but no love it seems.

**Comment by coreywillwhat** [comment]
The US endpoint has changed. This was pointed out in the arjenvrh branch.
For US you would need to use "https://app-api.my.aoa.audi.com/vgql/v1/graphql". I tried to look through the files of this branch to see where to replace it but couldn't find it.

**Comment by cyr-ius** [comment]
Up custom_component to 1.3.2
