### ISSUE TITLE
US Region Not Working

### ISSUE THREAD

**Issue by coreywillwhat** [cyr-ius/hass-audiconnect#41]
I've been using the arjevrh branch for quite some time. There have been various tweaks to keep it working, but as stated on the main page, its no longer maintained.

I'm following updates to audiconnectpy and keep trying to switch to this branch. So far the last 2 changes for US region have not worked.

Here are some logs. Let me know if there is any other way I can help.

```
2023-12-17 12:18:03.718 ERROR (MainThread) [custom_components.audiconnect.coordinator] Unexpected error fetching audiconnect data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 47, in _async_update_data
    await self.api.async_update()
  File "/usr/local/lib/python3.11/site-packages/audiconnectpy/api.py", line 58, in async_update
    for response in vehicles_response.getr("data.userVehicles", []):
TypeError: 'NoneType' object is not iterable
```

**Comment by eliasisrael** [comment]
I'm guessing that the audiconnectpy dependency needs to be updated to 1.4.5

**Comment by coreywillwhat** [comment]
ah yeah, didn't see it was still pointing to 1.4.4 in the manifest. I'll give it a shot. Thanks!

**Comment by eliasisrael** [comment]
I can confirm that if you update your manifest use 1.4.5, it works again

**Comment by cyr-ius** [comment]
Up custom_component to 1.3.2

**Comment by coreywillwhat** [comment]
Just loaded 1.3.2, confirm US region works now. Closing the issue. Thank you both!
