### ISSUE TITLE
Latest Home Assistant (2024.1) broke integration

### ISSUE THREAD

**Issue by hjaltij** [cyr-ius/hass-audiconnect#46]
**Describe the bug**
Home Assistant Core 2024.1 broke the integration.

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 12:29:31 AM (7 occurrences)
Last logged: 12:29:31 AM

Unexpected exception importing platform custom_components.audiconnect.switch
Unexpected exception importing platform custom_components.audiconnect.lock
Unexpected exception importing platform custom_components.audiconnect.select
Unexpected exception importing platform custom_components.audiconnect.device_tracker
Unexpected exception importing platform custom_components.audiconnect.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/audiconnect/sensor.py", line 12, in <module>
    from .entity import AudiEntity
  File "/config/custom_components/audiconnect/entity.py", line 11, in <module>
    from .helpers import (
  File "/config/custom_components/audiconnect/helpers.py", line 30, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument

**Comment by shuntfield** [comment]
Yes, confirm I am getting the same error, when updated to 2024.1

**Comment by bushbrother** [comment]
Confirming the same happens to me on upgrade.

**Comment by cyr-ius** [comment]
Fix , please try 1.4.7

**Comment by bushbrother** [comment]
Fixed for me, amazing! Thank you for speedy change.

**Comment by shuntfield** [comment]
Yup looks good here, thanks.
Before I had lots of entities such as front door window etc, they all seem to have disappeared. Not sure if its Audi thats caused that, only because it listed "AdBlue" and my car is a petrol car!

But fixed anyhow!

**Comment by hjaltij** [comment]
Awesome, thanks @cyr-ius!

**Comment by superpower10** [comment]
Everything worked fine for me till now…

Than I updated to 1.4.8 and didn‘t update to 2024.1.0 because it has a bug in the Enigma2 Integration in it.

1.4.8 doesn‘t work with 2023.12.4

**Comment by hjaltij** [comment]
Since this is fixed for 2024.1 I'm going to close this issue.
