### ISSUE TITLE
Error loading integration with 2.0.2-beta1

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#70]
Hi cyr-ius,

I tried your latest beta 2.0.2-beta1. It doesn't load with the following error. I realize you are still working on it, but wanted to let you as it might be useful information for you. I have an Audi e-tron 55.

Thanks for all your effort.

Logger: custom_components.audiconnect.coordinator
Bron: helpers/update_coordinator.py:315
integratie: Audi Connect (documentatie, problemen)
Eerst voorgekomen: 22:33:05 (4 gebeurtenissen)
Laatst gelogd: 22:34:09

Unexpected error fetching audiconnect data
Traceback (most recent call last):
  File "<string>", line 19, in __mashumaro_from_dict__
  File "<string>", line 7, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "start" of type datetime is missing in SingleTimer instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "<string>", line 4, in __mashumaro_from_dict__
  File "<string>", line 21, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "single_timer" of type SingleTimer in Timer has invalid value {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 10, in __mashumaro_from_dict__
  File "<string>", line 4, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "timers" of type Optional[list[Timer]] in ClimatisationTimersStatus has invalid value [{'id': 1, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}}, {'id': 2, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 31, in __mashumaro_from_dict__
  File "<string>", line 4, in __mashumaro_from_dict__
  File "<string>", line 12, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "climatisation_timers_status" of type Optional[ClimatisationTimersStatus] in ClimatisationTimers has invalid value {'carCapturedTimestamp': '2024-06-01T20:15:47Z', 'timers': [{'id': 1, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}}, {'id': 2, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 60, in _async_update_data
    await self.api.async_login()
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/api.py", line 65, in async_login
    await self.async_fetch_data(vinlist=vinlist)
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/api.py", line 92, in async_fetch_data
    await vehicle.async_update()
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/vehicle.py", line 94, in async_update
    vehicle_model = Model.from_dict(data)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 33, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "climatisation_timers" of type Optional[ClimatisationTimers] in Model has invalid value {'climatisationTimersStatus': {'carCapturedTimestamp': '2024-06-01T20:15:47Z', 'timers': [{'id': 1, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}}, {'id': 2, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2018-01-01T12:00:00', 'targetDateTimeLocal': '2018-01-01T12:00:00'}}]}}

**Comment by cyr-ius** [comment]
Please try latest version

**Comment by tieskuh** [comment]
It works! Thanks!
