### ISSUE TITLE
Unexpected error fetching audiconnect data

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#79]
It seems to have something to do with the location of the vehicle. The entire integration fails to update.
It recovers by itself after some time. Maybe the location is unknown at the time of the error and needs a try/catch.

```
Logger: custom_components.audiconnect.coordinator
Bron: helpers/update_coordinator.py:312
integratie: Audi Connect (documentatie, problemen)
Eerst voorgekomen: 09:56:28 (3 gebeurtenissen)
Laatst gelogd: 10:41:42

Unexpected error fetching audiconnect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 68, in _async_update_data
    await vehicle.async_update()
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/vehicle.py", line 123, in async_update
    self.position = Position.from_dict(position.get("data"))
                                       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by cyr-ius** [comment]
Fix to 2.1.1
