### ISSUE TITLE
Integration not loading

### ISSUE THREAD

**Issue by tieskuh** [cyr-ius/hass-audiconnect#88]
**Describe the bug**
Integration not loading

**Diagnostics file**
Not possible to download. Button is missing. Probably due to the integration not loading. This is a snippet from the debug log:
```
2024-08-08 09:02:33.038 ERROR (MainThread) [custom_components.audiconnect.coordinator] Unexpected error fetching audiconnect data
Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "<string>", line 9, in __unpack_literal_ClimatisationStatus_climatisation_state__8f224002508b417980845a69009c6118
ValueError: invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "climatisation_state" of type Optional[Literal['off', 'heating', 'cooling']] in ClimatisationStatus has invalid value 'invalid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 38, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "climatisation_status" of type Optional[ClimatisationStatus] in Climatisation has invalid value {'carCapturedTimestamp': '2024-08-08T01:00:15Z', 'remainingClimatisationTime_min': -256, 'climatisationState': 'invalid'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/coordinator.py", line 60, in _async_update_data
    await self.api.async_login()
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/api.py", line 65, in async_login
    await self.async_fetch_data(vinlist=vinlist)
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/api.py", line 92, in async_fetch_data
    await vehicle.async_update()
  File "/usr/local/lib/python3.12/site-packages/audiconnectpy/vehicle.py", line 100, in async_update
    vehicle_model = Model.from_dict(data)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 40, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "climatisation" of type Optional[Climatisation] in Model has invalid value {'climatisationSettings': {'carCapturedTimestamp': '2024-08-08T01:00:17Z', 'targetTemperature_C': 21, 'targetTemperature_F': 70, 'climatisationWithoutExternalPower': True, 'climatizationAtUnlock': False, 'windowHeatingEnabled': True, 'zoneFrontLeftEnabled': False, 'zoneFrontRightEnabled': False}, 'climatisationStatus': {'carCapturedTimestamp': '2024-08-08T01:00:15Z', 'remainingClimatisationTime_min': -256, 'climatisationState': 'invalid'}, 'windowHeatingStatus': {'windowHeatingStatus': [{'windowLocation': 'front', 'windowHeatingState': 'invalid'}, {'windowLocation': 'rear', 'windowHeatingState': 'invalid'}]}}
2024-08-08 09:03:59.226 ERROR (MainThread) [custom_components.audiconnect.coordinator] Unexpected error fetching audiconnect data
Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "<string>", line 9, in __unpack_literal_ClimatisationStatus_climatisation_state__8f224002508b417980845a69009c6118
ValueError: invalid
```

**Screenshots**
![image](https://github.com/user-attachments/assets/fab42c2b-4364-4642-a9e9-22a9ee8162e4)

**Additional context**
Might be related to HA update 2024.8 or it is just a coincidence

**Comment by tieskuh** [comment]
It started working again without any change.
The error seems to be that 'climatisationState' had the value 'invalid'. Maybe something you can change in the integration to prevent that state from crashing the entire integration.

**Comment by fdreckmann** [comment]
Same here

**Comment by tieskuh** [comment]
The error is back again. It seems to happen now and then.
